import type { Metadata } from 'next'

/* the props */
import "open-props/style";

/* optional imports that use the props */
import "open-props/normalize";
import "open-props/buttons";

import '@/styles/global.css'


import "@fontsource/work-sans";
import "@fontsource/merriweather";

import Header from "@/components/Header";
import Footer from '@/components/Footer';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <meta name="description" content="Bennjmann Redmans Portfolio"/>
        <meta name="viewport" content="width=device-width"/>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg"/>
        <title>Bennjmann Redman</title>
      </head>

      <body>
      <Header/>
      {children}
      <Footer/>
      </body>
      </html>
  )
}
